-- PadelX DEMO - Administrador de Pistas (Courts)
--
-- Incluye:
-- - Tabla public.courts (multi-tenant)
-- - Triggers seguros (tenant_id automático, updated_at, límite de 10 pistas por tenant)
-- - RLS + policies por rol (admin/manager crean y editan, solo admin elimina)
--
-- Requisito:
-- - Debe existir la función public.current_profile() (tenant_id, role, active).
--   Si no la tenés creada, podés reutilizar la que ya usamos en DEMO:
--
-- create or replace function public.current_profile()
-- returns table (tenant_id uuid, role text, active boolean)
-- language sql
-- stable
-- security definer
-- set search_path = public
-- set row_security = off
-- as $$
--   select p.tenant_id, p.role, p.active
--   from public.profiles p
--   where p.id = auth.uid()
--   limit 1
-- $$;

create table if not exists public.courts (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  name text not null,
  is_covered boolean not null default false,
  sort_order int not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists courts_tenant_id_idx on public.courts (tenant_id);
create index if not exists courts_tenant_sort_idx on public.courts (tenant_id, sort_order);

-- Triggers (defaults + updated_at + límite 10)
create or replace function public.courts_before_insert()
returns trigger
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
declare
  v_tenant uuid;
  v_count int;
  v_next_order int;
begin
  if new.tenant_id is null then
    select tenant_id into v_tenant from public.current_profile();
    new.tenant_id := v_tenant;
  end if;

  if new.tenant_id is null then
    raise exception 'tenant_no_asignado';
  end if;

  -- Límite de pistas por tenant (máx 10)
  select count(*) into v_count from public.courts c where c.tenant_id = new.tenant_id;
  if v_count >= 10 then
    raise exception 'max_courts_reached';
  end if;

  -- Orden automático por tenant
  if new.sort_order is null or new.sort_order <= 0 then
    select coalesce(max(c.sort_order), 0) + 1
      into v_next_order
    from public.courts c
    where c.tenant_id = new.tenant_id;
    new.sort_order := v_next_order;
  end if;

  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.courts_before_update()
returns trigger
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
begin
  -- Evitar mover una pista de tenant accidentalmente
  new.tenant_id := old.tenant_id;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_courts_before_insert on public.courts;
create trigger trg_courts_before_insert
before insert on public.courts
for each row
execute function public.courts_before_insert();

drop trigger if exists trg_courts_before_update on public.courts;
create trigger trg_courts_before_update
before update on public.courts
for each row
execute function public.courts_before_update();

-- RLS + Policies
alter table public.courts enable row level security;

DO $$
declare r record;
begin
  for r in (select policyname from pg_policies where schemaname='public' and tablename='courts') loop
    execute format('drop policy if exists %I on public.courts', r.policyname);
  end loop;
end$$;

-- SELECT: cualquier autenticado ve solo pistas de su tenant
create policy courts_select_tenant
on public.courts
for select
to authenticated
using (
  tenant_id = (select tenant_id from public.current_profile())
);

-- INSERT: admin/manager, activo, y dentro de su tenant
create policy courts_insert_admin_manager
on public.courts
for insert
to authenticated
with check (
  (select active from public.current_profile()) = true
  and (select role from public.current_profile()) in ('admin','manager')
  and tenant_id = (select tenant_id from public.current_profile())
);

-- UPDATE: admin/manager, activo, y dentro de su tenant
create policy courts_update_admin_manager
on public.courts
for update
to authenticated
using (
  (select active from public.current_profile()) = true
  and (select role from public.current_profile()) in ('admin','manager')
  and tenant_id = (select tenant_id from public.current_profile())
)
with check (
  (select active from public.current_profile()) = true
  and (select role from public.current_profile()) in ('admin','manager')
  and tenant_id = (select tenant_id from public.current_profile())
);

-- DELETE: solo admin, activo, y dentro de su tenant
create policy courts_delete_admin
on public.courts
for delete
to authenticated
using (
  (select active from public.current_profile()) = true
  and (select role from public.current_profile()) = 'admin'
  and tenant_id = (select tenant_id from public.current_profile())
);
